# Generated by Django 5.0.2 on 2024-03-13 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_present", models.BooleanField(default=True)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "date_modified",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClassSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "start_date_and_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "end_date_and_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_repeated", models.BooleanField(default=False)),
                (
                    "repeat_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "meeting_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CLASS_SESSION", "Class Sessions"),
                            ("WELLNESS_SESSION", "Well Session"),
                            ("GUEST_LECTURE", "Guest Lecture"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("venue", models.CharField(blank=True, default="", max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_modified", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=1000)),
                ("description", models.TextField(blank=True, default="N/A", null=True)),
                (
                    "date_created",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DECLINED", "Declined"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                (
                    "query_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FACILITY", "Facility"),
                            ("LOGISTICS", "Logistics"),
                            ("KITCHEN", "Kitchen"),
                        ],
                        default="FACILITY",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "date_modified",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QueryComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(blank=True, default="", null=True)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "date_modified",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
